config/routes.rb
TeatroDelBarrio::Application.routes.draw do

  

  get "landing/index"
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    

    root :to => 'polls#index'

    devise_for :users
    get "users/index"

    resources :taxonomies
    resources :terms
    resources :memberships
     match "massive_updated/",:to =>  "memberships#massive_update" , :via => [:post], :as => :massive_update_memberships

    resources :polls 
    match "vote/:question_id/:my_vote",:to =>  "votes#create" , :via => [:get], :as => :voting
    match "unvote/:question_id"       ,:to =>  "votes#destroy", :via => [:get], :as => :destroy_vote

    resources :admins
      match "admins/change_superadmin/:user_id",:to =>  "admins#change_superadmin" , :via => [:get], :as => :change_superadmin
    

  end
  
  
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: [:get, :post]
  match ''     , to: redirect("/#{I18n.default_locale}"), via: [:get, :post]

end

  

app/models/question.rb
class Question < ActiveRecord::Base


  belongs_to :poll

  serialize :answers_public
  serialize :answers_guest
  serialize :answers_member

  validates :matter , :presence => true

  after_initialize -> {setup_answers }

  def vote! user, params

    if self.poll.can_vote? user

      the_vote = (params == "yes") ? 1 : 0

      if user
        answers = user.member? ? self.answers_member : self.answers_guest
        answers[user.id] = the_vote
      else
        # check if public user has already voted

        answers_public[params.to_sym] += 1
      end

      self.save

    else
      errors[:poll] << "activerecord.errors.messages.the_poll_is_closed".t
      return false
    end

  end
  def destroy_vote! user

    if self.poll.open?
      self.answers_member.delete user.id if user.member?
      self.answers_guest.delete  user.id unless user.member?

      self.save
    else
      errors[:poll] << "activerecord.errors.messages.the_poll_is_closed".t
      return false

    end

  end



  def voted? user
    user ||= User.new
    return false unless user.email?
    return true  if (self.answers_guest.merge(self.answers_member)).has_key?(user.id)
    false

  end


  # singleton methods for answers
  def answers_count


    self.answers_count_yeses + self.answers_count_noes


  end

  def answers_count_yeses
    self.answers_yeses.count + answers_public[:yes].to_i
  end

  def answers_count_noes

    self.answers_noes.count + answers_public[:no].to_i

  end

  def answers_yeses

    answers = answers_guest.merge answers_member
    @yeses ||= answers.select { |key, value| value == 1 }
  end


  def answers_noes
    answers = answers_guest.merge answers_member
    @noes ||= answers.select { |key, value| value == 0 }
  end

  def answers_my_vote user
    if user.email?
      answers = answers_guest.merge answers_member
      answers[user.id] == 1 ? "yes" : "no" if user
    else
      "unknown"
    end
  end


  private

  def setup_answers
    self.answers_member ||= {}
    self.answers_guest  ||= {}
    self.answers_public ||= {yes:0, no:0}
  end

end

app/views/questions/_voting_buttons.html.erb
<% if  question.poll.allowed_voting?(current_user) %>
  <h4>
    <%= ("questions.you_voted_%s".t % "questions._#{question.answers_my_vote(current_user)}".t) if question.voted?(current_user) %>
    <%= ("questions.you_didn't_vote".t) unless question.voted?(current_user)||question.poll.open?  %>
    <%= ("questions.you_voted_%s".t % "questions._#{public_user_has_vote?(question)}".t)  if current_user.nil?&&public_user_has_vote?(question) %>
  </h4>
<%end%>

<% if can_vote? question %>
  <% if !question.voted?(current_user) %>
    <h5><%= "questions.my_vote".t  %></h5>
    <%= link_to "<span class='glyphicon glyphicon-ok-circle' style='color:green;'></span>".html_safe, voting_path(question, "yes"), :class => "btn btn-lg btn-default", title: "questions.vote_yes".t %>&nbsp;
    <%= link_to "<span class='glyphicon glyphicon-remove-circle' style='color:red;'></span>".html_safe, voting_path(question, "no") , :class => "btn btn-lg btn-default ", title: "questions.vote_no".t %>
  <% else %>
    <%= link_to "questions.vote_again".t, destroy_vote_path(question), :class => "btn btn-xs btn-info"  %>
  <% end %>
<% end %>