config/routes.rb
TeatroDelBarrio::Application.routes.draw do

  

  get "landing/index"
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    

    root :to => 'polls#index'

    devise_for :users
    get "users/index"

    resources :taxonomies
    resources :terms
    resources :memberships
     match "massive_updated/",:to =>  "memberships#massive_update" , :via => [:post], :as => :massive_update_memberships

    resources :polls 
    match "vote/:question_id/:my_vote",:to =>  "votes#create" , :via => [:get], :as => :voting
    match "unvote/:question_id"       ,:to =>  "votes#destroy", :via => [:get], :as => :destroy_vote

    resources :admins
      match "admins/change_superadmin/:user_id",:to =>  "admins#change_superadmin" , :via => [:get], :as => :change_superadmin
    

  end
  
  
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: [:get, :post]
  match ''     , to: redirect("/#{I18n.default_locale}"), via: [:get, :post]

end

  

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user, :foreign_key => :email,
            :primary_key => :email


  validates :email          , presence:true, uniqueness: true, email: true
   validates_uniqueness_of  :membership_code, allow_blank: true, allow_nil: true

  # Kaminari DSL
  paginates_per 30


  default_scope { order('email ASC') }

  def self.csv_desctructive



  end

  def parse_csv csv_string


    if (csv_string =~ /,/) > 0

      updatable_emails = csv_string.gsub!(/(\r\n|\n|\r)/,'').split(",") - Membership.all.pluck(:email)



    else


      updatable_emails = csv_string.gsub!(/(\r)/,'').split() - Membership.all.pluck(:email)


    end


    updatable_emails.each do |email|
      Membership.create email: email rescue self.errors.add(:massive_update, "#{email} ha fallado")
    end




  end







end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.page(params[:page])
    @membership  = Membership.new
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new


  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create

    @membership = Membership.new membership_params



    respond_to do |format|
      if @membership.save
        format.html { redirect_to :back , notice: ("memberships.member_added_%s".t % @membership.email ) }
        format.json { render action: 'show', status: :created, location: @membership }
      else

        format.html { redirect_to :back , warning: @membership.errors.to_s }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    @membership = Membership.find params[:id]
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to :back, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, @membership.errors }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = Membership.find params[:id]
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to :back , warning: ("memberships.member_deleted_%s".t % @membership.email )}
      format.json { head :no_content }
    end
  end

  def massive_update

    
    @membership = Membership.new
    
    @membership.parse_csv params[:the_file].read if params[:the_file].respond_to? :read
    redirect_to memberships_path

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def standard_a
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:email, :membership_code)
    end
end

app/views/memberships/index.html.erb
<h1><%= "memberships.members".t %></h1>
<%= paginate @memberships, :window => 2, html: {:class => "pull-right"} %>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th><%= "memberships.linked_user".t %></th>
      <th><%= "memberships.email".t %></th>
        <th><%= "memberships.active".t %></th>
        <th><%= "memberships.membership_code".t %></th>
        <th><%= "global.actions".t %>   </th>
    </tr>
  </thead>
  <tbody>
    <% @memberships.each do |membership|%>
            <tr id="member_<%= membership.id %>">
              <td>
                  <%=  membership.user ? "global._yes".t : "global._no".t  %>
              </td>
              <td>
                <%=   membership.email %>
              </td>
              <td> <%= membership.active %></td>
              <td>

                    <span> <%= membership.membership_code %></span>

                    <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, "#", class: "btn btn-xs btn-default pull-right" ,onClick: "$(this).next().removeClass('hidden');$(this).prev().toggle();$(this).remove();", title: "global.edit".t if allow?("memberships","update") %>
                    <div class="hidden col-2-md">
                      <%= form_for membership do |d| %>

                            <div class="input-group ">

                             <%= d.text_field :membership_code, :class => "form-control" ,:placeholder => "memberships.membership_code".t%>
                              <span class="input-group-btn">

                                <%= d.submit "global.send".t, :class => "btn  btn-primary " %>
                              </span>
                          </div>


                    </div>
                  <% end %>
              </td>
              <td><%= link_to  "<span class='glyphicon glyphicon-remove' ></span>".html_safe,  membership_path(membership),title: "global.delete".t ,class:"btn btn-xs btn-warning", :method => :delete, data:{confirm:"global.are_you_sure?".t} %></td>

            </tr>


    <%end %>
  </tbody>
</table>
<%= paginate @memberships, :window => 2 %>
<div class="row">
  <div class= "col-12-md col-12-xs ">
    <%= link_to "global.add".t,"#", id: "show-membership-form" ,
                    class: "btn btn-md btn-default",
                    onClick: "$(this).next().removeClass('hidden');$(this.remove())" if allow?("memberships","create") %>
    <div class="hidden dotted-shadowed col-md-5 col-xs-10 col-xs-offset-1">
      <%= form_for @membership do |d| %>
        <%= d.email_field :email, :class => "form-control col-3-md" ,:placeholder => "memberships.email".t%>
        <br/>
        <%= d.text_field :membership_code, :class => "form-control col-3-md" ,:placeholder => "memberships.membership_code".t%>
        <br/>

        <%= d.submit "global.create".t, :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<br/>
<div class="row">
  <div class= "col-12-md col-12-xs ">
    <%= link_to "memberships.massive_add".t,"#", id: "massive-membership-upload" ,
                    class: "btn btn-md btn-default",
                    onClick: "$(this).next().removeClass('hidden');$(this.remove())" if allow?("memberships","create") %>
    <div class="hidden dotted-shadowed col-md-5 col-xs-11 col-xs-offset-1">


      <%= form_tag massive_update_memberships_path, :multipart => true do |d| %>

        <div class="row">
          <%= file_field_tag "the_file",    class: "col-md-9 col-xs-10" %>
          <%= link_to "global.info".t, "#", class: "badge badge-default  show-tooltip col-xs-2 col-md-1", data:{placement:"top",toggle:"tooltip", title:"memberships.massive_add_tooltip".t} %>
        </div>
        <br/>
       <%= submit_tag "global.send_file".t, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>


<%= content_for :footer_scripts do %>

<script>

$(".show-tooltip").tooltip();

</script>

<% end %>