config/routes.rb
TeatroDelBarrio::Application.routes.draw do

  

  get "landing/index"
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    

    root :to => 'polls#index'

    devise_for :users
    get "users/index"

    resources :taxonomies
    resources :terms
    resources :memberships
     match "massive_updated/",:to =>  "memberships#massive_update" , :via => [:post], :as => :massive_update_memberships

    resources :polls 
    match "vote/:question_id/:my_vote",:to =>  "votes#create" , :via => [:get], :as => :voting
    match "unvote/:question_id"       ,:to =>  "votes#destroy", :via => [:get], :as => :destroy_vote

    resources :admins
      match "admins/change_superadmin/:user_id",:to =>  "admins#change_superadmin" , :via => [:get], :as => :change_superadmin
    

  end
  
  
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: [:get, :post]
  match ''     , to: redirect("/#{I18n.default_locale}"), via: [:get, :post]

end

  

app/views/admins/index.html.erb
<h1><%= "admins.admins_list".t %></h1>
<%= paginate @admins, :window => 2, html: {:class => "pull-right"} %>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th><%=   "users.email".t %></th>
      <% if allow? "admins", "change_superadmin" %>
        <th><%= "global.actions".t %>   </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin|%>
            <tr id="admin_<%= admin.id %>">

              <td>
                <%=   admin.email %>
              </td>

              <% if allow? "admins", "change_superadmin" %>
              <td>

                   <%= link_to  "<span class='glyphicon glyphicon-remove' ></span>".html_safe, admin_path(admin) , :method => :delete, data:{confirm:"global.are_you_sure?".t}, class:"btn btn-xs btn-warning", title: "global.delete".t %>
                 <% end %>
                <% if allow? "admins", "change_superadmin" %>

                <%= link_to "<span class='glyphicon glyphicon-asterisk' ></span>".html_safe, change_superadmin_path(admin.id), class:"show-tooltip btn btn-xs pull-right btn-info", data:{placement:"top",toggle:"tooltip", title:"admins.change_superadmin".t, confirm:"admins.are_you_sure_no_more_superadmin".t }%>


              </td>
              <% end %>

            </tr>


    <%end %>
  </tbody>
</table>
<%= paginate @admins, :window => 2 %>
<%if allow? "admins", "create" %>
  <div class="row">
    <div class= "col-12-md col-12-xs ">
      <%= link_to "global.add".t,"#", id: "show-admin-form" ,
                      class: "btn btn-md btn-default",
                      onClick: "$(this).next().removeClass('hidden');$(this.remove())" if allow?("memberships","create") %>
      <div class="hidden dotted-shadowed col-md-5 col-xs-10 col-xs-offset-1">
        <%= form_for @admin ,  url: admins_path do |d| %>
          <%= d.email_field :email, :class => "form-control col-3-md" ,:placeholder => "memberships.email".t%>
          <br/>
          <%= d.submit "global.create".t, :class => "btn btn-primary" %>
          <%= link_to "global.info".t, "#", class: "badge badge-default  show-tooltip pull-right", data:{placement:"top",toggle:"tooltip", title:"admins.email_should_belongs_to_user".t} %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= content_for :footer_scripts do %>

<script>

$(".show-tooltip").tooltip();

</script>

<% end %>