config/routes.rb
TeatroDelBarrio::Application.routes.draw do

  

  get "landing/index"
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

    

    root :to => 'polls#index'

    devise_for :users
    get "users/index"

    resources :taxonomies
    resources :terms
    resources :memberships
     match "massive_updated/",:to =>  "memberships#massive_update" , :via => [:post], :as => :massive_update_memberships

    resources :polls 
    match "vote/:question_id/:my_vote",:to =>  "votes#create" , :via => [:get], :as => :voting
    match "unvote/:question_id"       ,:to =>  "votes#destroy", :via => [:get], :as => :destroy_vote

    resources :admins
      match "admins/change_superadmin/:user_id",:to =>  "admins#change_superadmin" , :via => [:get], :as => :change_superadmin
    

  end
  
  
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: [:get, :post]
  match ''     , to: redirect("/#{I18n.default_locale}"), via: [:get, :post]

end

  

app/models/taxonomy.rb
class Taxonomy < Term

  #Taxonomies are terms with parent_id == 0
  default_scope {where(:parent_id => 0)}
  has_many :terms



  def get_linage




  end


end

app/controllers/taxonomies_controller.rb
class TaxonomiesController < ApplicationController

  def index

    @terms = Term.order("parent_id asc, name asc")
   # @terms = @terms.sort_by {|x| x[:parent_id]}
    @term = Term.new
    @taxonomies = Taxonomy.all



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @terms}
    end

  end





  def new

    @term = Term.new()
    @term.parent_id = params[:parent_id]
        respond_to do |format|
        format.html # index.html.erb
        format.js
        format.json { render json: @terms}
      end

  end
def show
end

def edit

  @term = Term.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @terms}
    end

end


  def create

    @term = Term.new(standard_attributes)



    respond_to do |format|
      if @term.save
        format.html {redirect_to(taxonomies_url, notice: t('messages.term_created'))}
      else
        format.html {redirect_to(taxonomies_url, notice: t('messages.term_not_created'))}
      end
    end


  end

  def update

    @term =  Term.find(params[:id])
    respond_to do |format|
     if @term.update_attributes(standard_attributes)
        format.html {redirect_to(taxonomies_url, notice: t('messages.term_created'))}
      else
        format.html {redirect_to(taxonomies_url, notice: t('messages.term_not_created'))}
     end
   end

  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    respond_to do |format|
      format.html { redirect_to taxonomies_url }
      format.js
      format.json { head :no_content }
    end
  end

    private

  def standard_attributes


    params.require(:term).permit(:name,:taxonomy_id,:parent_id)

  end


end

app/helpers/taxonomies_helper.rb
module TaxonomiesHelper
  
  def button_create_term(key, value , term)
    
    render(:partial => 'taxonomies/create_term_button', :locals =>{:key => key, :value => value, :term => term})
    
  end
  
  def check_sons(id)
    
    @terms.select {|x| x[:parent_id]==id}.length >0
  end
  
# Form field for taxonomies   
  def terms_field_for(taxonomy_id, object)
    taxonomy = Taxonomy.find taxonomy_id

    taxonomy_terms = OrderedArray.new(taxonomy.terms).order
    render "taxonomies/family_names/family_names", {:taxonomy_terms => taxonomy_terms,
                                                    :taxonomy => taxonomy,
                                                    :object => object}
    
  end
  
  def print_terms_for(object,*taxonomies)
    final_render ||= ""

    taxonomies.each do |taxonomy_arg|
      terms = object.terms.where(:taxonomy_id => taxonomy_arg)
      taxonomy = Taxonomy.find taxonomy_arg
      final_render += render("taxonomies/family_names/print_terms_for",
                      {:terms => terms,:taxonomy => taxonomy}) if terms.length > 0
    end
    final_render.html_safe
  end
  
  def terms_list(object)
    render "taxonomies/terms_list", :var => object
    
  end

end

app/views/taxonomies/_create_term.html.erb
<p>
  <div id="create-term-<%= @term.parent_id %>" style="">

  <%= form_for(@term,:url => taxonomies_path()) do |x| %>    
    <%= x.text_field :name, :style => "margin:0;" %>
    <%= x.hidden_field :parent_id, :value => @term.parent_id %>
    <%= x.submit "add term", :class => "btn btn-xs btn-primary", :method => "post" %>
  <% end %>
  </div>

</p>

app/views/taxonomies/_create_term_button.html.erb
  <a href="javascript:void(0)" onClick="$('#create-term-<%= key %>').toggle();$('#create-term-<%= key %> #term_name').focus();$(this).toggle()" class="btn btn-xs btn-default create-term"><span class="glyphicon glyphicon-plus"></span></a>

  <div id="create-term-<%= key %>" style="display:none">
  <%= form_for(term,:url => taxonomies_url) do |x| %>
    <div class="input-group">

      <%= x.text_field :name, :style => "margin:0;", :class =>"form-control"  %>
      <span class="input-group-btn">
            <%= x.submit t("taxonomies.add_term"), :class => "btn btn-primary" %>
        </span>


    </div><!-- /input-group -->
    <%= x.hidden_field :taxonomy_id, :value => key %>
  <% end %>

app/views/taxonomies/_edit_term.html.erb
  <li id="edit-term-<%= t.id %>" style="">

  <%= form_for(t,:url => taxonomy_path(t.id)) do |x| %>    
    <%= x.text_field :name, :style => "margin:0;" %>    
    <%= x.submit "update term", :class => "btn btn-medium btn-edit", :method => "post" %>
  <% end %>
  </li>

app/views/taxonomies/_list_elements.html.erb
         
   <% list.each do |f| %>
 <li id="term-<%= f.id %>" class="parent-<%= f.parent_id %>">
             <% if f.parent_id == 0 %>
                         
             <span class="deploy-button glyphicon glyphicon-chevron-right btn btn-xs" ></span>
             <% end %>
             <span id="term-<%= f.id %>" class="<%= "has-sons " if check_sons f.id%>" ><%= f.name %>
                <div class="action-buttons">
                  <%= link_to (raw("")), taxonomy_path( f.id),:method => "delete", data: {:confirm => "Deleting term \"#{f.name}\"?"},:remote => true , :class => "btn btn-xs glyphicon glyphicon-minus img-circle btn-destroy" , :alt => "#{t'taxonomies.remove_term'}", :title => "#{t'taxonomies.remove_term'}"%>
                  <%= link_to "",edit_taxonomy_path(f.id), class: "btn btn-xs glyphicon glyphicon-edit img-circle btn-edit",title:t("taxonomies.edit"),alt:t("taxonomies.edit"), remote: true%>
                  <%= link_to "",new_taxonomy_path(:parent_id => f.id),:class => "btn btn-xs  glyphicon glyphicon-arrow-down img-circle btn-edit",alt:t("taxonomies.add_child_term"),title:t("taxonomies.add_child_term"),:remote => true  %>
                </div>
             </span> 

             <% if check_sons f.id%>
                          
                      <% sublist = @list.select {|x| x[:parent_id]==f.id} %>
                      
               <ul>
                      
                      
                 <%= render "list_elements" ,:list => sublist %>
                 
                 <% @list.reject! {|x| x[:parent_id]==f.id} %>
                 </ul>
               
             <% end %>
             </li>
<%end %>
     

app/views/taxonomies/_terms_list.html.erb
<%  if var.terms.count != 0   %>
<div class="terms-list">
<em class="field-title"><%= t"taxonomies.terms" %>:</em>
  <ul class= "terms">
    
  <% var.terms.each {|x| concat "<li>#{x.name}</li>".html_safe}%>
   <div class= "clearfix"></div>
  </ul>
 
</div>
<% end %>

app/views/taxonomies/destroy.js.erb
$("#term-<%= @term.id %> .action-buttons").first().remove();

$("span#term-<%= @term.id %>").addClass("term-deleted");

app/views/taxonomies/edit.js.erb
$("#term-<%=@term.id%>").replaceWith("<%=j render('edit_term', :t=> @term) %>");

app/views/taxonomies/index.html.erb
<div  id="single-asset" class="col-md-7 ">
  <h1><%= t("misc.list_taxonomies")%></h1>
  <br/>
  <div class="panel-group taxonomies" id="accordion2">
   <% @taxonomies.each_with_index do |taxonomy, index|%>
   <div id="<%= "taxonomy_#{taxonomy.id}" %>" class="panel panel-default">
      <div class="panel-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="<%="#collapse#{index}" %>">
            <h4><%=  taxonomy.name %></h4>

        </a>
      </div>
      
      <% @list = @terms.select {|f| f["taxonomy_id"]== taxonomy.id } %>

      
      <div  id="<%="collapse#{index}" %>" class="panel-collapse collapse <%= "in" if index == 0 %>">
        <div class="panel-body">
      
          <ul>
            
           <%= render "list_elements" , :list => @list %>
          
          </ul>

          <%= button_create_term(taxonomy.id, (taxonomy.name), @term) %>
        </div> 
      </div> 
    </div> </div>
    <% end %>
  </div>
</div>
<%= content_for :footer_scripts do %>
  <script >

    $(document).ready(function(){
      window.taxonomies = new TdB.Taxonomies_Terms();

    })

  </script> 
<% end %>

app/views/taxonomies/new.js.erb
$("#term-<%=@term.parent_id%> div").first().replaceWith("<%=j render('create_term', :t=> @term) %>");